---
# tasks file for ahp-wireguard

- name: "Install required packages"
  tags:
    - packages
  ansible.builtin.package:
    name: "{{ ahp_wg_pkg_list }}"
    state: present

- name: "Fetch Private key - {{ ahp_wg_type }}"
  shell: "cat {{ inventory_hostname }}.key"
  register: result
  delegate_to: localhost

- name: "Use Private key in variable"
  set_fact:
    ahp_wg_privkey: "{{ result.stdout }}"

- name: "Fetch Peer Public key - {{ ahp_wg_type }}"
  shell: "cat {{ ahp_wg_peer_shortname }}.pub"
  register: result
  delegate_to: localhost

- name: "Use Peer Public key in variable"
  set_fact:
    ahp_wg_peer_pubkey: "{{ result.stdout }}"

- name: "Deploy config file - {{ ahp_wg_type }}"
  ansible.builtin.template:
    src: "templates/wg-{{ ahp_wg_type }}.j2"
    dest: "{{ ahp_wg_conf_path }}"
    owner: "root"
    group: "root"
    mode: "0600"
